Repository Indrajith-98/FTTU-interns, pull requests merged in 2025-01, with the labels that each got.

#13 Dev sabari
  .github/workflows/.build-merge.yml
  sabari/config.sh
  sabari/cpp_assignments/dummy.txt
  sabari/gdb_assignment_gets2025/.vscode/tasks.json
  sabari/gdb_assignment_gets2025/Assignment_1/Assignment_1
  sabari/gdb_assignment_gets2025/Assignment_1/Assignment_1.cpp
  sabari/gdb_assignment_gets2025/Assignment_1/Assignment_1.cpp:Zone.Identifier
  sabari/gdb_assignment_gets2025/Assignment_1/breakpoints.x
  sabari/gdb_assignment_gets2025/Assignment_1/out
  sabari/gdb_assignment_gets2025/Assignment_2/Assignment_2.cpp
  sabari/gdb_assignment_gets2025/Assignment_2/Assignment_2.cpp:Zone.Identifier
  sabari/gdb_assignment_gets2025/Assignment_2/out
  sabari/gdb_assignment_gets2025/Assignment_3/Assignment_3.cpp
  sabari/gdb_assignment_gets2025/Assignment_3/Assignment_3.cpp:Zone.Identifier
  sabari/gdb_assignment_gets2025/Assignment_3/input.txt
  sabari/gdb_assignment_gets2025/Assignment_3/input.txt:Zone.Identifier
  sabari/gdb_assignment_gets2025/Assignment_3/input2.txt
  sabari/gdb_assignment_gets2025/Assignment_3/out
  sabari/main.c
  sabari/python_assignments/dummy.txt
  sabari/tvm_assignments/dummy.txt
Labels: build-script-1

#21 removed the zoneidentifier file
  sabari/gdb_assignment_gets2025/Assignment_1/Assignment_1.cpp:Zone.Identifier
  sabari/gdb_assignment_gets2025/Assignment_1/breakpoints.x
  sabari/gdb_assignment_gets2025/Assignment_2/Assignment_2.cpp:Zone.Identifier
  sabari/gdb_assignment_gets2025/Assignment_3/Assignment_3.cpp:Zone.Identifier
  sabari/gdb_assignment_gets2025/Assignment_3/input.txt:Zone.Identifier
Labels: build-script-1

#17 Pravin - Add completed gdb assignments
  .DS_Store
  pravin/config.sh
  pravin/cpp_assignments/dummy.txt
  pravin/gdb_assignments/Assignment_1/Assignment_1
  pravin/gdb_assignments/Assignment_1/Assignment_1.cpp
  pravin/gdb_assignments/Assignment_1/Assignment_1.dSYM/Contents/Info.plist
  pravin/gdb_assignments/Assignment_1/Assignment_1.dSYM/Contents/Resources/DWARF/Assignment_1
  pravin/gdb_assignments/Assignment_1/Assignment_1.dSYM/Contents/Resources/Relocations/aarch64/Assignment_1.yml
  pravin/gdb_assignments/Assignment_1/Assignment_1_soln
  pravin/gdb_assignments/Assignment_1/Assignment_1_soln.cpp
  pravin/gdb_assignments/Assignment_1/Assignment_1_soln.dSYM/Contents/Info.plist
  pravin/gdb_assignments/Assignment_1/Assignment_1_soln.dSYM/Contents/Resources/DWARF/Assignment_1_soln
  pravin/gdb_assignments/Assignment_1/Assignment_1_soln.dSYM/Contents/Resources/Relocations/aarch64/Assignment_1_soln.yml
  pravin/gdb_assignments/Assignment_1/infrence.txt
  pravin/gdb_assignments/Assignment_1/mylog.txt
  pravin/gdb_assignments/Assignment_2/Assignment_2
  pravin/gdb_assignments/Assignment_2/Assignment_2.cpp
  pravin/gdb_assignments/Assignment_2/Assignment_2.dSYM/Contents/Info.plist
  pravin/gdb_assignments/Assignment_2/Assignment_2.dSYM/Contents/Resources/DWARF/Assignment_2
  pravin/gdb_assignments/Assignment_2/Assignment_2.dSYM/Contents/Resources/Relocations/aarch64/Assignment_2.yml
  pravin/gdb_assignments/Assignment_2/Assignment_2_soln
  pravin/gdb_assignments/Assignment_2/Assignment_2_soln.cpp
  pravin/gdb_assignments/Assignment_2/Assignment_2_soln.dSYM/Contents/Info.plist
  pravin/gdb_assignments/Assignment_2/Assignment_2_soln.dSYM/Contents/Resources/DWARF/Assignment_2_soln
  pravin/gdb_assignments/Assignment_2/Assignment_2_soln.dSYM/Contents/Resources/Relocations/aarch64/Assignment_2_soln.yml
  pravin/gdb_assignments/Assignment_2/infrence.txt
  pravin/gdb_assignments/Assignment_2/mylog.txt
  pravin/gdb_assignments/Assignment_3/Assignment_3
  pravin/gdb_assignments/Assignment_3/Assignment_3.cpp
  pravin/gdb_assignments/Assignment_3/Assignment_3.dSYM/Contents/Info.plist
  pravin/gdb_assignments/Assignment_3/Assignment_3.dSYM/Contents/Resources/DWARF/Assignment_3
  pravin/gdb_assignments/Assignment_3/Assignment_3.dSYM/Contents/Resources/Relocations/aarch64/Assignment_3.yml
  pravin/gdb_assignments/Assignment_3/Assignment_3_soln
  pravin/gdb_assignments/Assignment_3/Assignment_3_soln.cpp
  pravin/gdb_assignments/Assignment_3/Assignment_3_soln.dSYM/Contents/Info.plist
  pravin/gdb_assignments/Assignment_3/Assignment_3_soln.dSYM/Contents/Resources/DWARF/Assignment_3_soln
  pravin/gdb_assignments/Assignment_3/Assignment_3_soln.dSYM/Contents/Resources/Relocations/aarch64/Assignment_3_soln.yml
  pravin/gdb_assignments/Assignment_3/infrence.txt
  pravin/gdb_assignments/Assignment_3/input.txt
  pravin/gdb_assignments/Assignment_3/mylog.txt
  pravin/main.c
  pravin/python_assignments/dummy.txt
  pravin/tvm_assignments/dummy.txt
Labels: build-script-1

#41 Complete Image Manipulation Assignment - Pravin
  pravin/cpp_assignments/.DS_Store
  pravin/cpp_assignments/imageManipulation/.DS_Store
  pravin/cpp_assignments/imageManipulation/.gitignore
  pravin/cpp_assignments/imageManipulation/CMakeLists.txt
  pravin/cpp_assignments/imageManipulation/Functions/include/image_operations.h
  pravin/cpp_assignments/imageManipulation/Functions/src/adjust_contrast.cpp
  pravin/cpp_assignments/imageManipulation/Functions/src/adjust_highlights.cpp
  pravin/cpp_assignments/imageManipulation/Functions/src/adjust_saturation.cpp
  pravin/cpp_assignments/imageManipulation/Functions/src/adjust_shadows.cpp
  pravin/cpp_assignments/imageManipulation/Functions/src/convert_bgr_to_hsv.cpp
  pravin/cpp_assignments/imageManipulation/image1.jpeg
  pravin/cpp_assignments/imageManipulation/modifiedImages/bgr_to_hsv_converted.jpg
  pravin/cpp_assignments/imageManipulation/modifiedImages/contrast_adjusted.jpg
  pravin/cpp_assignments/imageManipulation/modifiedImages/highlight_adjusted.jpg
  pravin/cpp_assignments/imageManipulation/modifiedImages/saturation_adjusted.jpg
  pravin/cpp_assignments/imageManipulation/modifiedImages/shadow_adjusted.jpg
  pravin/cpp_assignments/imageManipulation/src/main.cpp
Labels: C++

#39 Clock Application Assignment (C++)
  Ayushmaan_Das/cpp_assignments/Clock_Assignment/Alarm.cpp
  Ayushmaan_Das/cpp_assignments/Clock_Assignment/README.md
  Ayushmaan_Das/cpp_assignments/Clock_Assignment/Stopwatch.cpp
  Ayushmaan_Das/cpp_assignments/Clock_Assignment/Timer.cpp
  Ayushmaan_Das/cpp_assignments/Clock_Assignment/main.cpp
  Ayushmaan_Das/cpp_assignments/Clock_Assignment/main.exe
  Ayushmaan_Das/cpp_assignments/Clock_Assignment/output.log
  Ayushmaan_Das/cpp_assignments/README.md
Labels: C++

#117 Added the Deep Learning Assignment
  Ayushmaan_Das/.gitattributes
  Ayushmaan_Das/README.md
  Ayushmaan_Das/python_assignments/Deep_Learning_TensorRT/.gitignore
  Ayushmaan_Das/python_assignments/Deep_Learning_TensorRT/1_model_training.py
  Ayushmaan_Das/python_assignments/Deep_Learning_TensorRT/2_hyperparameter_tuning.py
  Ayushmaan_Das/python_assignments/Deep_Learning_TensorRT/3_augmented_training.py
  Ayushmaan_Das/python_assignments/Deep_Learning_TensorRT/README.md
  Ayushmaan_Das/python_assignments/Deep_Learning_TensorRT/hypertuned_resnet34_fashion_mnist.onnx
  Ayushmaan_Das/python_assignments/Deep_Learning_TensorRT/hypertuned_resnet34_fashion_mnist.trt
  Ayushmaan_Das/python_assignments/Deep_Learning_TensorRT/hypertuned_resnet34_fashion_mnist/fingerprint.pb
  Ayushmaan_Das/python_assignments/Deep_Learning_TensorRT/hypertuned_resnet34_fashion_mnist/saved_model.pb
  Ayushmaan_Das/python_assignments/Deep_Learning_TensorRT/hypertuned_resnet34_fashion_mnist/variables/variables.data-00000-of-00001
  Ayushmaan_Das/python_assignments/Deep_Learning_TensorRT/hypertuned_resnet34_fashion_mnist/variables/variables.index
  Ayushmaan_Das/python_assignments/Deep_Learning_TensorRT/logs/converted_to_onnx.log
  Ayushmaan_Das/python_assignments/Deep_Learning_TensorRT/logs/tensorRT_optimization.log
  Ayushmaan_Das/python_assignments/Deep_Learning_TensorRT/requirements.txt
  Ayushmaan_Das/python_assignments/Deep_Learning_TensorRT/resnet34.py
  Ayushmaan_Das/python_assignments/Deep_Learning_TensorRT/stepwise_implementation.ipynb
  Ayushmaan_Das/python_assignments/Deep_Learning_TensorRT/utils/__init__.py
  Ayushmaan_Das/python_assignments/Deep_Learning_TensorRT/utils/model_converter.py
  Ayushmaan_Das/python_assignments/Deep_Learning_TensorRT/utils/plot_metrics.py
  Ayushmaan_Das/python_assignments/Deep_Learning_TensorRT/utils/predictor.py
  Ayushmaan_Das/python_assignments/README.md
  Ayushmaan_Das/python_assignments/requirements.txt
Labels: Python
